import {createPool} from './db.js';
import {createApp} from './app.js';
import {migrate} from './scripts/migrate.js';
import {bootstrapAdministrator} from './bootstrap.js';
const production=process.env.NODE_ENV==='production';
if(production&&(!process.env.APP_ORIGIN?.startsWith('https://')))throw Error('Production APP_ORIGIN must use HTTPS');
const razorpaySettings=['RAZORPAY_KEY_ID','RAZORPAY_KEY_SECRET','RAZORPAY_WEBHOOK_SECRET'],configured=razorpaySettings.filter(key=>process.env[key]);
if(configured.length&&configured.length!==razorpaySettings.length)throw Error('Configure all Razorpay settings together, or leave all three blank to disable paid checkout');
if(configured.length&&!process.env.TICKET_SECRET)throw Error('TICKET_SECRET is required when Razorpay checkout is configured');
const port=Number(process.env.PORT||5174),pool=createPool();
await migrate(pool);
if(await bootstrapAdministrator(pool))console.log('Initial administrator created; remove BOOTSTRAP_ADMIN_* environment variables and redeploy.');
await pool.query('SELECT 1');
const app=await createApp(pool,{origin:process.env.APP_ORIGIN||`http://localhost:${port}`,production});
const server=app.listen(port,process.env.HOST||(production?'0.0.0.0':'127.0.0.1'),()=>console.log(`Application listening on port ${port}; checkout ${configured.length?'enabled':'disabled'}`));
for(const signal of ['SIGTERM','SIGINT'])process.on(signal,()=>server.close(async()=>{await pool.end();process.exit(0);}));
